In [1]:
import pandas as pd
import numpy as np

In [4]:
logon = pd.read_csv("cleaned_logon.csv")
device = pd.read_csv("cleaned_device.csv")
file_data = pd.read_csv("cleaned_file.csv")

In [12]:
logon.shape
logon.head()
logon.info()
logon.describe()
logon.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 854859 entries, 0 to 854858
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   date         854859 non-null  object
 1   user         854859 non-null  object
 2   pc           854859 non-null  object
 3   activity     854859 non-null  object
 4   hour         854859 non-null  int64
 5   day          854859 non-null  int64
 6   month        854859 non-null  int64
 7   day_of_week  854859 non-null  int64
 8   is_weekend   854859 non-null  int64
 9   is_night     854859 non-null  int64
dtypes: int64(6), object(4)
memory usage: 65.2+ MB

Index(['date', 'user', 'pc', 'activity', 'hour', 'day', 'month', 'day_of_week',
       'is_weekend', 'is_night'],
      dtype='object')

In [23]:
logon['date'] = pd.to_datetime(logon['date'])

In [15]:
file_data.shape

(445581, 6)

In [16]:
file_data.head()

,date,user,pc,filename,content,hour
0,2010-01-02 07:23:14,MOH0273,PC-6699,EYPC9Y08.doc,D0-CF-11-E0-A1-B1-1A-E1 during difficulty over...,7
1,2010-01-02 07:26:19,MOH0273,PC-6699,N3LTSU3O.pdf,25-50-44-46-2D carpenters 25 landed strait dis...,7
2,2010-01-02 08:12:03,HPH0075,PC-2417,D3D3WC9W.doc,D0-CF-11-E0-A1-B1-1A-E1 union 24 declined impo...,8
3,2010-01-02 08:17:00,HPH0075,PC-2417,QCSW62YS.doc,D0-CF-11-E0-A1-B1-1A-E1 becoming period begin ...,8
4,2010-01-02 08:24:57,HSB0196,PC-8001,AU75JV6U.jpg,FF-D8,8

In [17]:
file_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445581 entries, 0 to 445580
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date      445581 non-null  object
 1   user      445581 non-null  object
 2   pc        445581 non-null  object
 3   filename  445581 non-null  object
 4   content   445581 non-null  object
 5   hour      445581 non-null  int64
dtypes: int64(1), object(5)
memory usage: 20.4+ MB

In [18]:
file_data.columns

Index(['date', 'user', 'pc', 'filename', 'content', 'hour'], dtype='object')

In [19]:
file_data['date'] = pd.to_datetime(file_data['date'])

In [25]:
device.shape

(405380, 5)

In [27]:
device.describe()

                                date           hour
count                         405380  405380.000000
mean   2010-08-28 13:27:51.007607552      12.405711
min              2010-01-02 07:21:06       0.000000
25%    2010-04-27 09:27:19.249999872      10.000000
50%              2010-08-20 15:14:13      13.000000
75%    2010-12-29 13:10:54.249999872      15.000000
max              2011-05-16 23:22:34      23.000000
std                              NaN       3.342539

In [26]:
device.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405380 entries, 0 to 405379
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date      405380 non-null  datetime64[ns]
 1   user      405380 non-null  object
 2   pc        405380 non-null  object
 3   activity  405380 non-null  object
 4   hour      405380 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 15.5+ MB

In [24]:
device.head()

                 date     user       pc    activity  hour
0 2010-01-02 07:21:06  MOH0273  PC-6699     Connect     7
1 2010-01-02 07:37:41  MOH0273  PC-6699  Disconnect     7
2 2010-01-02 07:59:11  HPH0075  PC-2417     Connect     7
3 2010-01-02 07:59:49  IIW0249  PC-0843     Connect     7
4 2010-01-02 08:04:26  IIW0249  PC-0843  Disconnect     8

In [28]:
device['date'] = pd.to_datetime(device['date'])

In [33]:
file_data.isnull().sum()

date        0
user        0
pc          0
filename    0
content     0
hour        0
dtype: int64

In [30]:
logon.isnull().sum()

date           0
user           0
pc             0
activity       0
hour           0
day            0
month          0
day_of_week    0
is_weekend     0
is_night       0
dtype: int64

In [32]:
device.isnull().sum()

date        0
user        0
pc          0
activity    0
hour        0
dtype: int64

In [35]:
merged_data = pd.read_csv("merged_dataset.csv")

In [36]:
merged_data.shape

(1703619, 17)

In [37]:
merged_data.head()

,date,user,pc_x,activity_x,hour_x,day,month,day_of_week,is_weekend,is_night,pc_y,activity_y,hour_y,pc,filename,content,hour
0,2010-01-04 08:09:00,AAE0190,PC-8915,Logon,8.0,4.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-04 18:20:00,AAE0190,PC-8915,Logoff,18.0,4.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-05 08:19:00,AAE0190,PC-8915,Logon,8.0,5.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-05 18:11:00,AAE0190,PC-8915,Logoff,18.0,5.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-06 08:09:00,AAE0190,PC-8915,Logon,8.0,6.0,1.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN